# Generated by Django 5.0.4 on 2024-04-24 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_remove_usuario_apellido_remove_usuario_contraseña_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='age',
            field=models.IntegerField(default=0),
        ),
    ]
