# Generated by Django 5.0.4 on 2024-04-26 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_alter_category_name_delete_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collaborator',
            name='category',
        ),
        migrations.DeleteModel(
            name='category',
        ),
        migrations.DeleteModel(
            name='Collaborator',
        ),
    ]
